:white_check_mark: Updates tests

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -11,6 +11,9 @@ jobs:
     steps:
       - uses: actions/checkout@v2
       - uses: ./
+        id: black_format
+        with:
+          fail_on_error: "false"
       - name: Check if code is left untouched (not formatted)
         run: |
           changed_files=$(git status --porcelain | wc -l)
@@ -20,6 +23,16 @@ jobs:
             echo "Changes detected!"
             exit 1
           fi
+      - name: Check 'is_formatted' output value
+        run: |
+          formatted=${{ steps.bumpr.outputs.current_version }}
+          if [[ ${formatted} != "false" ]];
+            echo "'is_formatted'  output invalid!"
+            exit 1
+          else
+            echo "'is_formatted'  output valid."
+          fi
+
 
   test-format:
     name: runner / black-format (format)
@@ -37,4 +50,13 @@ jobs:
             exit 1
           else
             echo "Changes detected!"
+          fi
+      - name: Check 'is_formatted' output value
+        run: |
+          formatted=${{ steps.bumpr.outputs.current_version }}
+          if [[ ${formatted} != "false" ]];
+            echo "'is_formatted'  output invalid!"
+            exit 1
+          else
+            echo "'is_formatted'  output valid."
           fi
